### ISSUE TITLE
Error message with the add raw php script

### ISSUE THREAD

**Issue by SemaphoreOxalis** [alexandreelise/j4x-api-examples#1]
The API connection seems ok, but I get this 
`{"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} {"errors":[{"title":"Field required: Title\nField required: Category"}]} `

**Comment by alexandreelise** [comment]
The errors or successful output are shown only for convenience to the user of the script. Internally all errors are captured and the code continues gracefully. When you see an error most of the time it is due to an already created article or some third-party plugin installed in your Joomla! site. Please refer to someone whom understands what the code does before trying to use it blindly. One last thing. This code is an example code NOT FOR PRODUCTION USE. Moreover it's opensource so you can fork it and modify it as you wish provided you follow the LICENSE used.
